#!/bin/bash-amd64

exec $@

case "$(uname -i)" in
    x86_64)
        exec $@
        ;;
    armv7l)
        exec /usr/bin/qemu-arm-static -execve $@
        ;;
    aarch64)
        exec /usr/bin/qemu-arm-static -execve $@
        ;;
    *)
        echo "Unsupported architecture $(uname -i)"
        exit 1
